/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;
import javax.swing.ImageIcon;

/**
 *
 * @author Trent
 */
public class Battle extends javax.swing.JFrame {
    Saves sav = new Saves();
    Monster enemy = new Monster(50, 0, 5);
    Combat player = new Combat(100, 1, 10, 3);
    ImageIcon playerImg = new ImageIcon(getClass().getResource("/resources/playerModel.png"));
    ImageIcon enemyImg = new ImageIcon(getClass().getResource("/resources/enemyModel.png"));
    int level = 0;
    /**
     * Creates new form Battle
     */
    public Battle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerHealthBar = new javax.swing.JProgressBar();
        enemyHealthBar = new javax.swing.JProgressBar();
        playerManaBar = new javax.swing.JProgressBar();
        enemyManaBar = new javax.swing.JProgressBar();
        playerTitleLabel = new javax.swing.JLabel();
        enemyTitleLabel = new javax.swing.JLabel();
        playerIcon = new javax.swing.JLabel();
        enemyIcon = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        attackButton = new javax.swing.JButton();
        magicButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        lvlTitle = new javax.swing.JLabel();
        playerStats = new javax.swing.JLabel();
        enemyStats = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Battle");

        playerHealthBar.setBackground(java.awt.Color.red);
        playerHealthBar.setForeground(java.awt.Color.darkGray);
        playerHealthBar.setValue(100);
        playerHealthBar.setString("Health");
        playerHealthBar.setStringPainted(true);

        enemyHealthBar.setMaximum(50);
        enemyHealthBar.setValue(50);
        enemyHealthBar.setStringPainted(true);
        enemyHealthBar.setString("Health");

        playerManaBar.setMaximum(3);
        playerManaBar.setValue(3);
        playerManaBar.setString("Mana: "+player.getMana());
        playerManaBar.setStringPainted(true);

        playerTitleLabel.setText("Player");

        enemyTitleLabel.setText("Enemy");

        playerIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playerIcon.setIcon(playerImg);

        enemyIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enemyIcon.setIcon(enemyImg);

        log.setColumns(20);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        attackButton.setText("Attack");
        attackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attackButtonActionPerformed(evt);
            }
        });

        magicButton.setText("Fireball");
        magicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magicButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next Battle");
        nextButton.setEnabled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        lvlTitle.setText("Level 1");

        playerStats.setText("Armor: 1   Damage: 10");

        enemyStats.setText("Armor: 0   Damage: 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerManaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(playerTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemyTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyManaBar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lvlTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(enemyHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attackButton)
                            .addComponent(magicButton)
                            .addComponent(playerStats))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enemyStats)
                            .addComponent(nextButton)
                            .addComponent(enemyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerHealthBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerManaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enemyManaBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerTitleLabel)
                    .addComponent(enemyTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(enemyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerStats)
                    .addComponent(enemyStats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(attackButton)
                    .addComponent(nextButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magicButton)
                    .addComponent(saveButton)
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void enemyTurn(){
        int enemyDamageDealt = enemy.getDamage()-player.getDefense();
        player.changeHealth(-enemyDamageDealt);
        playerHealthBar.setValue(player.getHealth());
        playerHealthBar.setString("Health:"+player.getHealth());
        log.append("Enemy dealt "+enemyDamageDealt+" damage to the player\n");
    }
    public void damageEnemy(int damage){
        enemy.changeHealth(-damage);
        enemyHealthBar.setValue(enemy.getHealth());
        enemyHealthBar.setString("Health:"+enemy.getHealth());
        log.append("Player dealt "+damage+" damage to the enemy\n");
        if(enemy.getHealth()<=0){
            attackButton.setEnabled(false);
            magicButton.setEnabled(false);
            enemyIcon.setIcon(null);
            log.append("Player defeated the enemy!\n");
            level++;
            log.append("You have beaten level "+level+"\n");
            nextButton.setEnabled(true);
        }
        else{
            enemyTurn();}
    }
    
    private void attackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attackButtonActionPerformed
        int damageDealt = player.getDamage()-enemy.getDefense();
        damageEnemy(damageDealt);
    }//GEN-LAST:event_attackButtonActionPerformed

    private void magicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magicButtonActionPerformed
        if(player.getMana()>0){
            damageEnemy(25);
            player.useMana(1);
            playerManaBar.setValue(player.getMana());
            playerManaBar.setString("Mana: "+player.getMana());
        }
        else{
            log.append("Not enough mana\n");
        }
    }//GEN-LAST:event_magicButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        nextButton.setEnabled(false); 
        attackButton.setEnabled(true);
        magicButton.setEnabled(true);
        lvlTitle.setText("Level "+level);
        
        player.changeHealth(player.getMaxHealth()-player.getHealth());
        Monster enemy = new Monster(50+(10*level), level, 5+level);
        
        enemyStats.setText("Armor: "+enemy.getDefense()+"   Damage: "+enemy.getDamage());
        enemyIcon.setIcon(enemyImg);
        enemyHealthBar.setMaximum(enemy.getHealth());
        enemyHealthBar.setValue(enemy.getHealth());
        playerHealthBar.setValue(player.getHealth());
    }//GEN-LAST:event_nextButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        sav.save("lvl", ""+level);
        sav.save("mana", ""+player.getMana());
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        level = sav.load("lvl");
        
    }//GEN-LAST:event_loadButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attackButton;
    private javax.swing.JProgressBar enemyHealthBar;
    private javax.swing.JLabel enemyIcon;
    private javax.swing.JProgressBar enemyManaBar;
    private javax.swing.JLabel enemyStats;
    private javax.swing.JLabel enemyTitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextArea log;
    private javax.swing.JLabel lvlTitle;
    private javax.swing.JButton magicButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JProgressBar playerHealthBar;
    private javax.swing.JLabel playerIcon;
    private javax.swing.JProgressBar playerManaBar;
    private javax.swing.JLabel playerStats;
    private javax.swing.JLabel playerTitleLabel;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
